# AutopenBench Improved local challenge containers
services:
    vm0:
        platform: linux/amd64
        build: ./vm0
        image: vm0
        container_name: vm0
        tty: true
        init: true
        networks:
            target_net:
                ipv4_address: 192.168.5.0
        restart: unless-stopped

    vm1:
        platform: linux/amd64
        build: ./vm1
        image: vm1
        container_name: vm1
        tty: true
        init: true
        networks:
            target_net:
                ipv4_address: 192.168.5.1
        restart: unless-stopped

    vm2:
        platform: linux/amd64
        build: ./vm2
        image: vm2
        container_name: vm2
        tty: true
        init: true
        networks:
            target_net:
                ipv4_address: 192.168.5.2
        ports:
            - 8080:8080
        command: bash -c "catalina.sh run && \
                          tail -f /dev/null"
        restart: unless-stopped

    vm3:
        platform: linux/amd64
        build: ./vm3
        image: vm3
        container_name: vm3
        tty: true
        init: true
        networks:
            target_net:
                ipv4_address: 192.168.5.3
        command: bash -c "
                    service ssh start &&
                    tail -f /dev/null"
        restart: unless-stopped

    vm4:
        platform: linux/amd64
        build: ./vm4
        image: vm4
        container_name: vm4
        tty: true
        init: true
        networks:
            target_net:
                ipv4_address: 192.168.5.4
        command: bash -c " httpd -D FOREGROUND &&
                    tail -f /dev/null"
        restart: unless-stopped

    vm5:
        platform: linux/amd64
        build: ./vm5
        image: vm5
        container_name: vm5
        tty: true
        init: true
        networks:
            target_net:
                ipv4_address: 192.168.5.5
        command: bash -c "tail -f /dev/null"
        restart: unless-stopped

    vm6:
        platform: linux/amd64
        build: ./vm6
        image: vm6
        container_name: vm6
        tty: true
        init: true
        networks:
            target_net:
                ipv4_address: 192.168.5.6
        restart: unless-stopped

    vm7:
        platform: linux/amd64
        build: ./vm7
        image: vm7
        container_name: vm7
        tty: true
        init: true
        networks:
            target_net:
                ipv4_address: 192.168.5.7
        restart: unless-stopped

    vm8:
        platform: linux/amd64
        build: ./vm8
        image: vm8
        container_name: vm8
        tty: true
        init: true
        networks:
            target_net:
                ipv4_address: 192.168.5.8
        restart: unless-stopped

    vm9:
        platform: linux/amd64
        build: ./vm9
        image: vm9
        container_name: vm9
        tty: true
        init: true
        networks:
            target_net:
                ipv4_address: 192.168.5.9
        restart: unless-stopped

    vm10:
        platform: linux/amd64
        build: ./vm10
        image: vm10
        container_name: vm10
        tty: true
        init: true
        networks:
            target_net:
                ipv4_address: 192.168.5.10
        restart: unless-stopped

# Network definition
networks:
    target_net:
        external: true
